### PR TITLE
Expose granax instance on node

### PR DESCRIPTION
**Pull request by stoically**
To be able to work with the granax instance created inside kad-onion I needed to expose it and thought adding the whole instantiated plugin as property on the node, so its possible to access `node.onion.tor`, would be OK. Thanks again for your work and sorry for the PR spam.

Best regards

### CODE REVIEW

**Comment by bookchin** [comment]
I don't really have a huge issue with this, but are you not able to do `node.onion = plugin(opts);` from your own paclage to get the desired result?

**Comment by stoically** [comment]
If I'm not mistaken you mean with `plugin(opts);` in this case calling the exported function from `kad-onion` itself? In this case the returned result is a function which instantiates a new instance of the plugin, so I have no access to data (like the tor `socksPort` or the granax instance itself at `tor`) already assigned to the plugin instance in use by `kad`. If I'm missing something here please let me know.

**Comment by bookchin** [comment]
Ah, you're absolutely right, my mistake. I am accessing the plugin and granax instance like you described in orcproject/orc, but the plugin actually should already be doing this here: https://github.com/kadtools/kad-onion/blob/master/index.js#L39

**Comment by stoically** [comment]
Ha, I didn't see that. Even the same property name. Works just fine, thanks!

**Pull request closed without merging**
